### ISSUE TITLE
Fix to allow app to support multiple zones

### ISSUE THREAD

**Issue by ardweebno** [drj-io/bhyve-zone-interval#1]
Issue:  The index.js script currently does not support multiple zones.  

Fix:  Updates to index.js and config.js to support multiple zones and number of times per zone to run.

[updates.zip](https://github.com/drj-io/bhyve-zone-interval/files/7448000/updates.zip)

**Comment by drj-io** [comment]
Hi, sorry it took a year+. I like this feature so I updated the current version to support an array of zones.  While I didn't use your code directly, it basically uses the same concept. Thanks a lot for the suggestion! Now I can set it all up and it'll blow out my whole system!
